spring:
  application:
    name: configclient
  cloud:
    config:
      label: temp
      profile: dev1
      #uri: http://localhost:8888/
      discovery:
        enabled: true
        service-id: configserver
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8882